apiVersion: v1
kind: Secret
metadata:
  name: neutron-secret
  namespace: {{ .Namespace }}
stringData:
  DatabasePassword: password
  NeutronKeystoneAuthPassword: foobar123
  TransportUrl: amqp://osp:passw0rd@amq-interconnect.openstack.svc:5672
